#!/usr/bin/env bash

set -e

# @cmd Run the binary without building
# @arg args*  Arguments to pass to the binary
# @meta default-subcommand
run() {
    go run . "${argc_args[@]}"
}

# @cmd Prepares a development environment
dev() {
    go mod tidy
    ls *.go | entr -c -r go run .
}

# @cmd Buils the binary
build() {
    go build
}

# See more details at https://github.com/sigoden/argc
eval "$(argc --argc-eval "$0" "$@")"
